### PR TITLE
fix version in readme.md and script.

### PR DESCRIPTION
**Pull request by ky0ncheng**
fix version in readme.md and script.

### CODE REVIEW

**Comment by toleda** [comment]
Thanks, merged.

**Comment by ky0ncheng** [comment]
I try your audio kext, but my speaks not work.
My motherboard model is MSI Z97 Gaming 7 with alc1150.
I try your script with inject method (1).
After rebooting.
The system audio setting appears 4 options.


But none is worked.
thx.

**Comment by toleda** [comment]
What motherboard audio port color are the speakers connected for each of the 4 SysPrefs selections?

**Comment by ky0ncheng** [comment]
Oh~ It's OK~
THX~

**Pull request merged**
